require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

RSpec:
  Language:
    ExampleGroups:
      Regular:
        - context
        - describe
        - wrap_context
      Skipped:
        - xcontext
        - xdescribe
        - xwrap_context
      Focused:
        - fcontext
        - fdescribe
        - fwrap_context
    Includes:
      Examples:
        - finclude_contract
        - finclude_examples
        - fwrap_examples
        - include_contract
        - include_examples
        - wrap_examples
        - xinclude_contract
        - xinclude_examples
        - xwrap_examples

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  IgnoredPatterns:
    - '\A\s*#'
  Max: 80

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_contract*.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/ExampleWording:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - spec/integration/**/*_spec.rb

RSpec/HookArgument:
  EnforcedStyle: example

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/ClassAndModuleChildren:
  Enabled: false
